server:
  servlet:
    contextPath: /
  error:
    include-message: always
spring:
  datasource:
    url: jdbc:h2:mem:mydb
    username: sa
    password: password
    driverClassName: org.h2.Driver
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    show-sql: false
    properties:
      hibernate:
        ddl-auto: none
        jdbc:
          time_zone: UTC
        format_sql: true
  h2:
    console.enabled: true