CREATE TABLE IF NOT EXISTS BRANDS(ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, NAME CHAR(50));
CREATE TABLE IF NOT EXISTS PRODUCTS(ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY, NAME CHAR(50));

CREATE TABLE IF NOT EXISTS PRICES(
	PRICE_ID BIGINT GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
	BRAND_ID BIGINT NOT NULL,
	START_DATE TIMESTAMP NOT NULL,
	END_DATE TIMESTAMP NOT NULL,
	PRICE_LIST INTEGER NOT NULL,
	PRODUCT_ID BIGINT NOT NULL,
	PRIORITY INTEGER NOT NULL,
	PRICE DECIMAL(5, 2) NOT NULL,
	CURR CHAR(3) NOT NULL,
	FOREIGN KEY (BRAND_ID) REFERENCES BRANDS(ID)
);